ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ZHMUYKF-SM18457"
      user: ""
      role: "ACCOUNTADMIN"
      database: "ECOMMERCE_DB"
      warehouse: "COMPUTE_WH"
      schema: "DEV_ANALYTICS"
      threads: 4
    prod:
      type: snowflake
      account: "ZHMUYKF-SM18457"
      user: ""
      role: "ACCOUNTADMIN"
      database: "ECOMMERCE_DB"
      warehouse: "COMPUTE_WH"
      schema: "ANALYTICS"
      threads: 4
